/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_AveragerInit(void);
extern void test_AveragerS8Running(void);
extern void test_AveragerU8Running(void);
extern void test_AveragerS16Running(void);
extern void test_AveragerU16Running(void);
extern void test_AveragerS32Running(void);
extern void test_AveragerU32Running(void);

extern void test_AveragerS8Reset(void);
extern void test_AveragerS16Reset(void);
extern void test_AveragerS32Reset(void);

extern void test_AveragerU8Reset(void);
extern void test_AveragerU16Reset(void);
extern void test_AveragerU32Reset(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "averager_test.c";
  UnityBegin();
  RUN_TEST(test_AveragerInit, 1);
  RUN_TEST(test_AveragerS8Running, 2);
  RUN_TEST(test_AveragerU8Running, 3);
  RUN_TEST(test_AveragerS16Running, 4);
  RUN_TEST(test_AveragerU16Running, 5);
  RUN_TEST(test_AveragerS32Running, 6);
  RUN_TEST(test_AveragerU32Running, 7);
  
  RUN_TEST(test_AveragerS8Reset, 8);
  RUN_TEST(test_AveragerS16Reset, 9);
  RUN_TEST(test_AveragerS32Reset, 10);
  
  RUN_TEST(test_AveragerU8Reset, 11);
  RUN_TEST(test_AveragerU16Reset, 12);
  RUN_TEST(test_AveragerU32Reset, 13);
  
  return (UnityEnd());
}
