/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_ThermistorInit(void);
extern void test_ValidAt25Degrees(void);
extern void test_ValidBetweenMinus30And50(void);
extern void test_Divider(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "thermistor_test.c";
  UnityBegin();
  RUN_TEST(test_ThermistorInit, 0);
  RUN_TEST(test_ValidAt25Degrees, 1);
  RUN_TEST(test_ValidBetweenMinus30And50, 2);
  RUN_TEST(test_Divider, 3);
  return (UnityEnd());
}
