import os
import logging

def get_logger():
	return logging.getLogger(__name__)

env = Environment(ENV=os.environ)

logging.basicConfig(level=logging.INFO)

cppflags = ["-Wall", "-Wextra", "-g"]

target = "TaskRunner.test"

test_objects = [
	Object('TaskRunner.test.cpp', CPPPATH="../", CPPFLAGS=cppflags),
	Object('../TaskRunner.cpp', CPPPATH="../", CPPFLAGS=cppflags)
]


program = env.Program(test_objects, LIBS=['cppunit'], CC='g++')
target_cmd = "./{0}/{0}.test".format(target)
test_alias = env.Alias(target, [program], program[0].path)
env.AlwaysBuild(test_alias)
