import time

unix_time = str(int(time.time()))
unix_time_chars = ','.join(list(unix_time))

t = time.gmtime()
unix_time_struct = '''.tm_year = %s, .tm_mon = %s, .tm_mday = %s, .tm_hour = %s, .tm_min = %s, .tm_sec = %s, .tm_wday = %s, .tm_yday = %s, .tm_isdst = %s''' % (t.tm_year-1900, t.tm_mon-1, t.tm_mday, t.tm_hour, t.tm_min, t.tm_sec, t.tm_wday, t.tm_yday, t.tm_isdst) 
    

with open("compiletime.h", "w") as w:
    w.write('''
	/* This file is autogenerated by compiletime.py */
	#ifndef _COMPILE_TIME_H_
	#define _COMPILE_TIME_H_
	
	// Compile time as UNIX epoch time
	#define COMPILE_TIME_INT (UNIX_TIMESTAMP)%s
	
	#define COMPILE_TIME_STR "%s"
	
	//Compile time as array of digits
	#define COMPILE_TIME_DIGITS { %s }
	
	// Compile time as C time struct
	#define COMPILE_TIME_STRUCT { %s }
	#endif
	
	''' % (unix_time, unix_time, unix_time_chars, unix_time_struct)
    )
