import os
import logging

def get_logger():
	return logging.getLogger(__name__)

env = Environment(ENV=os.environ)

library_path = os.path.expanduser(env['ENV']['CODE_LIBRARY_PATH'])
logging.basicConfig(level=logging.INFO)

cpppath = [".", "#../", library_path]
cppdefines = ["TEST_HARNESS"]
cppflags = ["-Wall", "-Wextra"]

for target in COMMAND_LINE_TARGETS:
	conscript = target+"/SConscript"
	test_objects = SConscript(conscript, exports='cpppath cppdefines cppflags')

	program = env.Program(test_objects, LIBS=['cppunit'], CC='g++')
	target_cmd = "./{0}/{0}.test".format(target)
	test_alias = env.Alias(target, [program], program[0].path)
	env.AlwaysBuild(test_alias)