/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_AddingNodes(void);
extern void test_CountingNodes(void);
extern void test_RemovingHeadNodes(void);
extern void test_RemovingMiddleNodes(void);
extern void test_RemovingTailNodes(void);
extern void test_TraversingNodes(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "util_time_test.c";
  UnityBegin();
  RUN_TEST(test_AddingNodes, 57);
  RUN_TEST(test_CountingNodes, 58);
  RUN_TEST(test_TraversingNodes, 62);
  RUN_TEST(test_RemovingHeadNodes, 59);
  RUN_TEST(test_RemovingMiddleNodes, 60);
  RUN_TEST(test_RemovingTailNodes, 61);

  return (UnityEnd());
}
