/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_RingBufInit(void);
extern void test_AddOneItem(void);
extern void test_MultipleItems(void);
extern void test_AddToFull(void);
extern void test_AddOverFull(void);
extern void test_GetItems(void);
extern void test_PopItems(void);
extern void test_GetMultipleItems(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "ringbuf_test.c";
  UnityBegin();
  RUN_TEST(test_RingBufInit, 1);
  RUN_TEST(test_AddOneItem, 2);
  RUN_TEST(test_MultipleItems, 3);
  RUN_TEST(test_AddToFull, 4);
  RUN_TEST(test_AddOverFull, 5)
  RUN_TEST(test_GetItems, 6);
  RUN_TEST(test_PopItems, 7);
  RUN_TEST(test_GetMultipleItems, 8);
  
  return (UnityEnd());
}
