Import('cpppath', 'cppdefines', 'cppflags')

cpppath += ["../../../utility", '../../ringbuf']

objects = [
	Object('ringbuf.test.cpp', CPPPATH=cpppath, CPPDEFINES=cppdefines, CPPFLAGS=cppflags),
	Object('../../ringbuf/ringbuf.cpp', CPPPATH=cpppath, CPPDEFINES=cppdefines, CPPFLAGS=cppflags, CC='g++')
]
Return('objects')
