/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_InitHandler(void);
extern void test_Update(void);
extern void test_UpdateWithDebouncing(void);
extern void test_NoRepeatInit(void);
extern void test_NoRepeatOnlyInvokesCallbacksOnce(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UNITY_BEGIN();
  RUN_TEST(test_InitHandler, 0);
  RUN_TEST(test_Update, 1);
  RUN_TEST(test_UpdateWithDebouncing, 2);
  RUN_TEST(test_NoRepeatInit, 3);
  RUN_TEST(test_NoRepeatOnlyInvokesCallbacksOnce, 4);
  
  return (UnityEnd());
}
