/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);

extern void test_recipIntegerDegrees(void);
extern void test_recipTenthsDegrees(void);

extern void test_mirrorIntegerDegreesAboutZero(void);
extern void test_mirrorIntegerDegreesAboutNonZero(void);

extern void test_mirrorTenthDegreesAboutZero(void);
extern void test_mirrorTenthDegreesAboutNonZero(void);

extern void test_mirrorTenthsDegrees(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "util_angle_test.c";
  UnityBegin();
  RUN_TEST(test_recipIntegerDegrees, 0);
  RUN_TEST(test_recipTenthsDegrees, 1);
  
  RUN_TEST(test_mirrorIntegerDegreesAboutZero, 2);
  RUN_TEST(test_mirrorIntegerDegreesAboutNonZero, 3);

  RUN_TEST(test_mirrorTenthDegreesAboutZero, 4);
  RUN_TEST(test_mirrorTenthDegreesAboutNonZero, 5);

  return (UnityEnd());
}
