/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_GenerateEmptySequence(void);
extern void test_GenerateConstantSequence(void);
extern void test_GenerateConstantSequenceWithRollover(void);
extern void test_GenerateRisingLinearRampWithUnityStep(void);
extern void test_GenerateRisingLinearRampWithBigStep(void);
extern void test_GenerateFallingLinearRampWithUnityStep(void);
extern void test_GenerateFallingLinearRampWithBigStep(void);
//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "util_sequence_generator_test.c";
  UnityBegin();
  RUN_TEST(test_GenerateEmptySequence, 1);
  RUN_TEST(test_GenerateConstantSequence, 2);
  RUN_TEST(test_GenerateConstantSequenceWithRollover, 3);
  RUN_TEST(test_GenerateRisingLinearRampWithUnityStep, 4);
  RUN_TEST(test_GenerateRisingLinearRampWithBigStep, 5);
  RUN_TEST(test_GenerateFallingLinearRampWithUnityStep, 4);
  RUN_TEST(test_GenerateFallingLinearRampWithBigStep, 5);
  return (UnityEnd());
}
