/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_ZeroReturnsNull(void);
extern void test_GetWithinBounds(void);
extern void test_GetOutsideBounds(void);
extern void test_GetExactBounds(void);
extern void test_GetOneByteAtATime(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "memorypool_test.c";
  UnityBegin();
  RUN_TEST(test_ZeroReturnsNull, 56);
  RUN_TEST(test_GetWithinBounds, 57);
  RUN_TEST(test_GetOutsideBounds, 58);
  RUN_TEST(test_GetExactBounds, 59);
  RUN_TEST(test_GetOneByteAtATime, 60);
  
  return (UnityEnd());
}
