/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_U8Format(void);
extern void test_S8Format(void);
extern void test_U16Format(void);
extern void test_S16Format(void);
extern void test_S32Format(void);
extern void test_RightAlignDoesNotModifyFullString(void);
extern void test_RightAlignDoesNotModifyRightAlignedString(void);
extern void test_RightAlignAlignsFromLeft(void);
extern void test_RightAlignAlignsFromMiddle(void);
extern void test_RightAlignAlignsWithEmbeddedSpaces(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "averager_test.c";
  UnityBegin();
  RUN_TEST(test_U8Format, 1);
  RUN_TEST(test_S8Format, 2);
  RUN_TEST(test_U16Format, 3);
  RUN_TEST(test_S16Format, 4);
  RUN_TEST(test_S32Format, 5);
  RUN_TEST(test_RightAlignDoesNotModifyFullString, 6);
  RUN_TEST(test_RightAlignDoesNotModifyRightAlignedString, 7);
  RUN_TEST(test_RightAlignAlignsFromLeft, 8);
  RUN_TEST(test_RightAlignAlignsFromMiddle, 9);
  RUN_TEST(test_RightAlignAlignsWithEmbeddedSpaces, 10);
  return (UnityEnd());
}
